name: Deploy to gh-pages branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare static output
        run: |
          set -e
          rm -rf site
          mkdir -p site
          cp -v index.html site/
          if [ -f 404.html ]; then cp -v 404.html site/; fi
          if [ -f style.css ]; then cp -v style.css site/; fi
          mkdir -p site/dist
          cp -vr dist/* site/dist/
          touch site/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
          force_orphan: true


